# Generated by Django 3.1.4 on 2020-12-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nuban', 'Nuban')], default='nuban', max_length=120)),
                ('currency', models.CharField(default='NGN', max_length=10, null=True)),
                ('name', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('recipient_code', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.accountdetails')),
            ],
            options={
                'verbose_name': 'Transfer Recipient',
                'verbose_name_plural': 'Transfer Recipients',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_code', models.CharField(max_length=200)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(blank=True, default='NGN', max_length=10, null=True)),
                ('source', models.CharField(choices=[('balance', 'Balance')], default='balance', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('otp', 'Otp'), ('success', 'Success')], default='pending', max_length=100)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.recipient')),
            ],
        ),
    ]
