# Generated by Django 3.1.4 on 2021-01-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_remove_accountdetails_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
