# Generated by Django 3.1.4 on 2021-01-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_refund_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subaccount',
            old_name='share',
            new_name='percentage_charge',
        ),
        migrations.RemoveField(
            model_name='transactionsplit',
            name='integration',
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='subaccount_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='split_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='SplitAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.PositiveBigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.subaccount')),
            ],
        ),
        migrations.AlterField(
            model_name='transactionsplit',
            name='subaccounts',
            field=models.ManyToManyField(blank=True, to='payment.SplitAccount'),
        ),
    ]
