# Generated by Django 3.1.4 on 2020-12-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('customer', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('error', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gateway_response', models.CharField(blank=True, max_length=150, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=150, null=True)),
                ('currency', models.CharField(blank=True, default='NGN', max_length=150, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('fees_split', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.log')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.source')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.subaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='subaccounts',
            field=models.ManyToManyField(through='transactions.TransactionSubAccount', to='payment.SubAccount'),
        ),
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.history')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.log')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='history',
            field=models.ManyToManyField(through='transactions.LogHistory', to='transactions.History'),
        ),
    ]
