# Generated by Django 3.1.4 on 2020-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('long_cocde', models.CharField(blank=True, max_length=120, null=True)),
                ('gateway', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
