# Generated by Django 3.1.4 on 2020-12-31 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('plan_code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('interval', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('biannually', 'Biannually')], default='monthly', max_length=120)),
                ('amount', models.PositiveBigIntegerField()),
                ('send_invoices', models.BooleanField(default=True)),
                ('hosted_page', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=True)),
                ('hosted_page_url', models.CharField(blank=True, max_length=120, null=True)),
                ('currency', models.CharField(blank=True, default='NGN', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_code', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('start', models.IntegerField()),
                ('email_token', models.CharField(max_length=120)),
                ('next_payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.source')),
            ],
        ),
    ]
