# Generated by Django 3.1.4 on 2021-01-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
